### ISSUE TITLE
multiple projects / results

### ISSUE THREAD

**Issue by fruitl00p** [Qafoo/QualityAnalyzer#13]
Is it possible to group _all_ result files into a single 'packaged' directory for serving?

My idea is to have analyze dump all ouput into a 'named' subdirectory of ```data/``` that would hold everything. The thing i'm still working out is the initial page of loading from the right starting point. It would allow analyzing various projects using a single instance and integrating it into our CI setup for every build... Currently I'm trying to alter all the JSX files to allow subdir selection by adding an ```Application``` class which would (currently) serve as a root aside from ```/``` (when starting at ```data/```

From your standpoint: is this a right thing to do, or should i just stop and rebind my docker container to different ```/data``` volumes so that /data inside the container points to a different build? :)

**Comment by kore** [comment]
My idea was to bundle `data/`, `assets/` & `index.html` and let (for example Jenkins) serve that tree with the HTML plugin. At some point I wanted to introduce something like a `bundle` or `copy` command which copies those to a specified directory.

That would keep the interface simple and let Jenkins handle the displaying & removing of the files.

If you have a better idea of handling this I am happy to discuss this.

**Comment by fruitl00p** [comment]
My idea was to give the analyze command a ```targetDir``` option and always move/copy the index.html to the ```targetDir```. The assets could be shared / are static anyway and could just as easily be loaded from an offsite CDN (i.e. github pages) That way i could hit the ```targetDir``` straight from the browser (or move that as an artifact from the CI server) and have everything in place...

**Comment by kore** [comment]
I'd prefer a dedicated command to reduce the respective complexity – and in most build pipelines it shouldn't be hard to call `analyze` a second time, right?

Additionally I refrained from using CDN until now since I often run this kind of tools in foreign company networks and with workshop participants. Internet can be really slow there and especially Github tends to block requests after a couple of requests.

So I would suggest a `bundle` or `copy` command with a target directory which then copies over everything. Optionally we could a `--cdn` option which does certain replacements in the `index.html` to use a CDN (maybe even Github) and omits the `assets/` folder.

**Comment by kore** [comment]
Please check out if https://github.com/Qafoo/QualityAnalyzer/pull/15 works for you. Using Github directly as a CDN does not work, because of https://github.com/blog/1482- – using a third party service for this feels wrong but works for now.

The links are still broken when serving from a subdirectory, even you can click around. Loading the `source.zip` does not work though. React-router probably requires some tweaking for that.
