### ISSUE TITLE
Using CS config

### ISSUE THREAD

**Issue by JeroenDeDauw** [Qafoo/QualityAnalyzer#52]
When running the analyzer, it generates a non-usable code style violations report for many of my projects, as they use a different standard than this tool. They do have phpmd.xml and phpcs.xml rule files in their root, though these appear to be ignored by the analyzer. Is there an option to have those be used? (I'm not seeing anything in the README or the help command output.)

**Comment by kore** [comment]
If you want custom execution you can use the CLI flags `--phpmd=<file>` and `--checkstyle=<file>` to reference existing analysis files from your build process.

I do not want to support all possible options of all involved tools through the `analyze` CLI, since this would clutter the CLI too much. Even changing the CWD would probably not suffice since one usually analyses the `src/` dir and not the project root…

**Comment by Mte90** [comment]
Also in my case I want to use another codesniffer standard that I have on my system, there is way for use it?

**Comment by kore** [comment]
I added a section to the README showing ways to customize tool execution: https://github.com/Qafoo/QualityAnalyzer#customize-tools

**Comment by Mte90** [comment]
Thank you!

**Comment by Mte90** [comment]
Doesn't explain how to use my custom xml file, I have tried with that:
`qualityanalyzer ./.qualityanalyzer.xml`
Without successful...

**Comment by kore** [comment]
Those are ant build files. I will improve the documentation regarding this.
