### ISSUE TITLE
Could not find project.json.

### ISSUE THREAD

**Issue by yohann-teisseire** [Qafoo/QualityAnalyzer#54]
Hi,

I have installed Qafoo on Wamp and i have this error : 
Could not find project.json. Run `bin/analyze analyze path/t/source` and reload.

What's wrong ?

Thanks,

**Comment by kore** [comment]
You have to run the mentioned shell script (`bin/analyze analyze path/to/source`) to produce the analysis results. There is no web UI for that.

See also the README: https://github.com/Qafoo/QualityAnalyzer#usage for usage details

**Comment by yohann-teisseire** [comment]
yeah, i have executed : bin/analyse analyse c/wamp/www/QualityAnalyser/src/php/, but nothing happened.

**Comment by kore** [comment]
I do not have access to any Window systems so that I cannot debug it myself.

What do you mean with "nothing happened"?

* Did the command run?
* Did the command produce any output? (It always should)
* Did the command produce any errors?

If that seemed to have worked please check the `data/` folder in the checkout: Does it contain a `project.json` file?

If this is the case you are left with debugging the JavaScript code. Please use a recent and modern browser.

**Comment by yohann-teisseire** [comment]
When i execute : bin/analyse analyse c/wamp/www/QualityAnalyser/src/php/
i have this : bash: bin bin/analyse : No such file or directory ( i have tried lot of path).

there is no project.json in folder called "data"

I use the last version of Firefox

**Comment by kore** [comment]
This script should be executed with php: https://github.com/Qafoo/QualityAnalyzer/blob/master/bin/analyze

You can try `php(.exe) /path/to/analyze analyze /path/to/your/source`.
