### ISSUE TITLE
Generate static HTML pages for results

### ISSUE THREAD

**Issue by theofidry** [Qafoo/QualityAnalyzer#7]
Having to use `bin/analyzer serve` prevent use from being able to host the result on say GitHub Pages for example. And as it's a static result, it doesn't make much sense to require a webserver for it, something like the HTML results of PHPUnit or PhpMetrics would be appreciated!

**Comment by kore** [comment]
The results are static files, you can (probably) serve them from any webserver. Just copy everything in `assets/` `data/` and `index.html` to some random webserver directory.

This is not documented since I did not verify yet if this works in any subdirectory even all assets are already referenced using relative URLs.
